/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.github.richygreat.scsra.dto;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class RoleDtoV1 extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3498681643004401769L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"RoleDtoV1\",\"namespace\":\"com.github.richygreat.scsra.dto\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"roleName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.String id;
  @Deprecated public java.lang.String roleName;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public RoleDtoV1() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param roleName The new value for roleName
   */
  public RoleDtoV1(java.lang.String id, java.lang.String roleName) {
    this.id = id;
    this.roleName = roleName;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return roleName;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.String)value$; break;
    case 1: roleName = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.String getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.String value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'roleName' field.
   * @return The value of the 'roleName' field.
   */
  public java.lang.String getRoleName() {
    return roleName;
  }

  /**
   * Sets the value of the 'roleName' field.
   * @param value the value to set.
   */
  public void setRoleName(java.lang.String value) {
    this.roleName = value;
  }

  /**
   * Creates a new RoleDtoV1 RecordBuilder.
   * @return A new RoleDtoV1 RecordBuilder
   */
  public static com.github.richygreat.scsra.dto.RoleDtoV1.Builder newBuilder() {
    return new com.github.richygreat.scsra.dto.RoleDtoV1.Builder();
  }

  /**
   * Creates a new RoleDtoV1 RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new RoleDtoV1 RecordBuilder
   */
  public static com.github.richygreat.scsra.dto.RoleDtoV1.Builder newBuilder(com.github.richygreat.scsra.dto.RoleDtoV1.Builder other) {
    return new com.github.richygreat.scsra.dto.RoleDtoV1.Builder(other);
  }

  /**
   * Creates a new RoleDtoV1 RecordBuilder by copying an existing RoleDtoV1 instance.
   * @param other The existing instance to copy.
   * @return A new RoleDtoV1 RecordBuilder
   */
  public static com.github.richygreat.scsra.dto.RoleDtoV1.Builder newBuilder(com.github.richygreat.scsra.dto.RoleDtoV1 other) {
    return new com.github.richygreat.scsra.dto.RoleDtoV1.Builder(other);
  }

  /**
   * RecordBuilder for RoleDtoV1 instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<RoleDtoV1>
    implements org.apache.avro.data.RecordBuilder<RoleDtoV1> {

    private java.lang.String id;
    private java.lang.String roleName;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.github.richygreat.scsra.dto.RoleDtoV1.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.roleName)) {
        this.roleName = data().deepCopy(fields()[1].schema(), other.roleName);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing RoleDtoV1 instance
     * @param other The existing instance to copy.
     */
    private Builder(com.github.richygreat.scsra.dto.RoleDtoV1 other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.roleName)) {
        this.roleName = data().deepCopy(fields()[1].schema(), other.roleName);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.String getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.github.richygreat.scsra.dto.RoleDtoV1.Builder setId(java.lang.String value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.github.richygreat.scsra.dto.RoleDtoV1.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'roleName' field.
      * @return The value.
      */
    public java.lang.String getRoleName() {
      return roleName;
    }

    /**
      * Sets the value of the 'roleName' field.
      * @param value The value of 'roleName'.
      * @return This builder.
      */
    public com.github.richygreat.scsra.dto.RoleDtoV1.Builder setRoleName(java.lang.String value) {
      validate(fields()[1], value);
      this.roleName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'roleName' field has been set.
      * @return True if the 'roleName' field has been set, false otherwise.
      */
    public boolean hasRoleName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'roleName' field.
      * @return This builder.
      */
    public com.github.richygreat.scsra.dto.RoleDtoV1.Builder clearRoleName() {
      roleName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public RoleDtoV1 build() {
      try {
        RoleDtoV1 record = new RoleDtoV1();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.String) defaultValue(fields()[0]);
        record.roleName = fieldSetFlags()[1] ? this.roleName : (java.lang.String) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
